
---
# tasks file for redis

- name: Install Redis
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Configure Redis from template
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: '0644'
  notify:
    - Restart Redis

- name: Ensure Redis is running
  service:
    name: redis-server
    state: started
    enabled: yes
